# Generated by Django 6.0.6 on 2026-06-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['order'], 'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.AlterModelOptions(
            name='servicebenefit',
            options={'ordering': ['pk'], 'verbose_name': 'service benefit', 'verbose_name_plural': 'service benefits'},
        ),
        migrations.AlterModelOptions(
            name='servicedeliverable',
            options={'ordering': ['pk'], 'verbose_name': 'service deliverable', 'verbose_name_plural': 'service deliverables'},
        ),
    ]
