# Generated by Django 6.0.6 on 2026-06-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_branchoffice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name'], 'verbose_name': 'client'},
        ),
        migrations.AlterModelOptions(
            name='technology',
            options={'ordering': ['name'], 'verbose_name': 'technology', 'verbose_name_plural': 'technologies'},
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='is_headquarters',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='technology',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=80),
        ),
    ]
