# Generated by Django 6.0.6 on 2026-06-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_hr_permissions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobapplication',
            options={'ordering': ['-created_at'], 'verbose_name': 'job application', 'verbose_name_plural': 'job applications'},
        ),
        migrations.AlterModelOptions(
            name='jobopening',
            options={'ordering': ['-posted_at'], 'verbose_name': 'job opening', 'verbose_name_plural': 'job openings'},
        ),
    ]
