# Generated by Django 6.0.6 on 2026-06-27 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed')], default='ongoing', max_length=20)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('project_value', models.CharField(blank=True, max_length=80)),
                ('duration', models.CharField(blank=True, max_length=60)),
                ('team_size', models.PositiveIntegerField(blank=True, null=True)),
                ('overview', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('solution', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='projects/thumbs/')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='core.client')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='core.industry')),
                ('technologies', models.ManyToManyField(blank=True, related_name='projects', to='core.technology')),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('caption', models.CharField(blank=True, max_length=180)),
                ('order', models.IntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'project gallery',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField()),
                ('title', models.CharField(blank=True, max_length=150)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='projects.project')),
            ],
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['status', 'is_featured'], name='projects_pr_status_2cea5d_idx'),
        ),
    ]
