# Generated by Django 6.0.6 on 2026-06-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_beforeaftergallery_projectmilestone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='projectdeliverable',
            options={'ordering': ['pk'], 'verbose_name': 'project deliverable', 'verbose_name_plural': 'project deliverables'},
        ),
        migrations.AlterModelOptions(
            name='projectvideo',
            options={'ordering': ['pk'], 'verbose_name': 'project video', 'verbose_name_plural': 'project videos'},
        ),
    ]
