# Generated by Django 6.0.6 on 2026-06-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='enquiry',
            options={'ordering': ['-created_at'], 'verbose_name': 'enquiry', 'verbose_name_plural': 'enquiries'},
        ),
    ]
