# Generated by Django 6.0.6 on 2026-07-01 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_enquiry_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_type',
            field=models.CharField(choices=[('general', 'General'), ('sales', 'Sales / Consultation'), ('support', 'Technical Support'), ('factory_visit', 'Book Factory Visit')], db_index=True, default='general', max_length=20),
        ),
    ]
