-- NexForge — full schema DDL generated by Django (reference only).
-- This is the EXACT SQL Django runs during `migrate`. Do NOT hand-run it
-- against a database that already has these tables. To (re)create the
-- schema, run: python manage.py migrate  (Django owns the schema).


-- ===== [APP] accounts.0001_roles =====
BEGIN;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;

-- ===== [FRAMEWORK] admin.0001_initial =====
BEGIN;
--
-- Create model LogEntry
--
CREATE TABLE "django_admin_log" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action_time" timestamp with time zone NOT NULL, "object_id" text NULL, "object_repr" varchar(200) NOT NULL, "action_flag" smallint NOT NULL CHECK ("action_flag" >= 0), "change_message" text NOT NULL, "content_type_id" integer NULL, "user_id" integer NOT NULL);
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_content_type_id_c4bce8eb_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "django_admin_log" ADD CONSTRAINT "django_admin_log_user_id_c564eba6_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "django_admin_log_content_type_id_c4bce8eb" ON "django_admin_log" ("content_type_id");
CREATE INDEX "django_admin_log_user_id_c564eba6" ON "django_admin_log" ("user_id");
COMMIT;

-- ===== [FRAMEWORK] admin.0002_logentry_remove_auto_add =====
BEGIN;
--
-- Alter field action_time on logentry
--
-- (no-op)
COMMIT;

-- ===== [FRAMEWORK] admin.0003_logentry_add_action_flag_choices =====
BEGIN;
--
-- Alter field action_flag on logentry
--
-- (no-op)
COMMIT;

-- ===== [FRAMEWORK] auth.0001_initial =====
BEGIN;
--
-- Create model Permission
--
CREATE TABLE "auth_permission" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(50) NOT NULL, "content_type_id" integer NOT NULL, "codename" varchar(100) NOT NULL);
--
-- Create model Group
--
CREATE TABLE "auth_group" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(80) NOT NULL UNIQUE);
CREATE TABLE "auth_group_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "group_id" integer NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model User
--
CREATE TABLE "auth_user" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NOT NULL, "is_superuser" boolean NOT NULL, "username" varchar(30) NOT NULL UNIQUE, "first_name" varchar(30) NOT NULL, "last_name" varchar(30) NOT NULL, "email" varchar(75) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL);
CREATE TABLE "auth_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" integer NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "auth_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" integer NOT NULL, "permission_id" integer NOT NULL);
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_codename_01ab375a_uniq" UNIQUE ("content_type_id", "codename");
ALTER TABLE "auth_permission" ADD CONSTRAINT "auth_permission_content_type_id_2f476e4b_fk_django_co" FOREIGN KEY ("content_type_id") REFERENCES "django_content_type" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_permission_content_type_id_2f476e4b" ON "auth_permission" ("content_type_id");
CREATE INDEX "auth_group_name_a6ea08ec_like" ON "auth_group" ("name" varchar_pattern_ops);
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_permission_id_0cd325b0_uniq" UNIQUE ("group_id", "permission_id");
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissions_group_id_b120cbf9_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_group_permissions" ADD CONSTRAINT "auth_group_permissio_permission_id_84c5c92e_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_group_permissions_group_id_b120cbf9" ON "auth_group_permissions" ("group_id");
CREATE INDEX "auth_group_permissions_permission_id_84c5c92e" ON "auth_group_permissions" ("permission_id");
CREATE INDEX "auth_user_username_6821ab7c_like" ON "auth_user" ("username" varchar_pattern_ops);
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_group_id_94350c0c_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_user_id_6a12ed8b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_user_groups" ADD CONSTRAINT "auth_user_groups_group_id_97559544_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_user_groups_user_id_6a12ed8b" ON "auth_user_groups" ("user_id");
CREATE INDEX "auth_user_groups_group_id_97559544" ON "auth_user_groups" ("group_id");
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_permission_id_14a6b632_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "auth_user_user_permissions" ADD CONSTRAINT "auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "auth_user_user_permissions_user_id_a95ead1b" ON "auth_user_user_permissions" ("user_id");
CREATE INDEX "auth_user_user_permissions_permission_id_1fbb5f2c" ON "auth_user_user_permissions" ("permission_id");
COMMIT;

-- ===== [FRAMEWORK] auth.0002_alter_permission_name_max_length =====
BEGIN;
--
-- Alter field name on permission
--
ALTER TABLE "auth_permission" ALTER COLUMN "name" TYPE varchar(255);
COMMIT;

-- ===== [FRAMEWORK] auth.0003_alter_user_email_max_length =====
BEGIN;
--
-- Alter field email on user
--
ALTER TABLE "auth_user" ALTER COLUMN "email" TYPE varchar(254);
COMMIT;

-- ===== [FRAMEWORK] auth.0004_alter_user_username_opts =====
BEGIN;
--
-- Alter field username on user
--
-- (no-op)
COMMIT;

-- ===== [FRAMEWORK] auth.0005_alter_user_last_login_null =====
BEGIN;
--
-- Alter field last_login on user
--
ALTER TABLE "auth_user" ALTER COLUMN "last_login" DROP NOT NULL;
COMMIT;

-- ===== [FRAMEWORK] auth.0007_alter_validators_add_error_messages =====
BEGIN;
--
-- Alter field username on user
--
-- (no-op)
COMMIT;

-- ===== [FRAMEWORK] auth.0008_alter_user_username_max_length =====
BEGIN;
--
-- Alter field username on user
--
ALTER TABLE "auth_user" ALTER COLUMN "username" TYPE varchar(150);
COMMIT;

-- ===== [FRAMEWORK] auth.0009_alter_user_last_name_max_length =====
BEGIN;
--
-- Alter field last_name on user
--
ALTER TABLE "auth_user" ALTER COLUMN "last_name" TYPE varchar(150);
COMMIT;

-- ===== [FRAMEWORK] auth.0010_alter_group_name_max_length =====
BEGIN;
--
-- Alter field name on group
--
ALTER TABLE "auth_group" ALTER COLUMN "name" TYPE varchar(150);
COMMIT;

-- ===== [FRAMEWORK] auth.0011_update_proxy_permissions =====
BEGIN;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;

-- ===== [FRAMEWORK] auth.0012_alter_user_first_name_max_length =====
BEGIN;
--
-- Alter field first_name on user
--
ALTER TABLE "auth_user" ALTER COLUMN "first_name" TYPE varchar(150);
COMMIT;

-- ===== [FRAMEWORK] authtoken.0001_initial =====
BEGIN;
--
-- Create model Token
--
CREATE TABLE "authtoken_token" ("key" varchar(40) NOT NULL PRIMARY KEY, "created" timestamp with time zone NOT NULL, "user_id" integer NOT NULL UNIQUE);
ALTER TABLE "authtoken_token" ADD CONSTRAINT "authtoken_token_user_id_35299eff_fk_auth_user_id" FOREIGN KEY ("user_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "authtoken_token_key_10f0b77e_like" ON "authtoken_token" ("key" varchar_pattern_ops);
COMMIT;

-- ===== [FRAMEWORK] authtoken.0002_auto_20160226_1747 =====
BEGIN;
--
-- Change Meta options on token
--
-- (no-op)
--
-- Alter field created on token
--
-- (no-op)
--
-- Alter field key on token
--
-- (no-op)
--
-- Alter field user on token
--
-- (no-op)
COMMIT;

-- ===== [FRAMEWORK] authtoken.0003_tokenproxy =====
BEGIN;
--
-- Create proxy model TokenProxy
--
-- (no-op)
COMMIT;

-- ===== [FRAMEWORK] authtoken.0004_alter_tokenproxy_options =====
BEGIN;
--
-- Change Meta options on tokenproxy
--
-- (no-op)
COMMIT;

-- ===== [APP] blog.0001_initial =====
BEGIN;
--
-- Create model BlogCategory
--
CREATE TABLE "blog_blogcategory" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(120) NOT NULL, "slug" varchar(50) NOT NULL UNIQUE);
--
-- Create model BlogPost
--
CREATE TABLE "blog_blogpost" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "title" varchar(200) NOT NULL, "slug" varchar(50) NOT NULL UNIQUE, "summary" text NOT NULL, "body" text NOT NULL, "featured_image" varchar(100) NULL, "is_featured" boolean NOT NULL, "published_at" timestamp with time zone NULL, "author_id" integer NULL, "category_id" bigint NOT NULL);
CREATE INDEX "blog_blogcategory_slug_7996de7a_like" ON "blog_blogcategory" ("slug" varchar_pattern_ops);
ALTER TABLE "blog_blogpost" ADD CONSTRAINT "blog_blogpost_author_id_ffcc150f_fk_auth_user_id" FOREIGN KEY ("author_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "blog_blogpost" ADD CONSTRAINT "blog_blogpost_category_id_0e9835dd_fk_blog_blogcategory_id" FOREIGN KEY ("category_id") REFERENCES "blog_blogcategory" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "blog_blogpost_slug_9e84ade1_like" ON "blog_blogpost" ("slug" varchar_pattern_ops);
CREATE INDEX "blog_blogpost_author_id_ffcc150f" ON "blog_blogpost" ("author_id");
CREATE INDEX "blog_blogpost_category_id_0e9835dd" ON "blog_blogpost" ("category_id");
CREATE INDEX "blog_blogpo_publish_e75c11_idx" ON "blog_blogpost" ("published_at" DESC);
COMMIT;

-- ===== [APP] careers.0001_initial =====
BEGIN;
--
-- Create model JobOpening
--
CREATE TABLE "careers_jobopening" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "slug" varchar(50) NOT NULL UNIQUE, "department" varchar(120) NOT NULL, "location" varchar(150) NOT NULL, "employment_type" varchar(20) NOT NULL, "experience" varchar(80) NOT NULL, "description" text NOT NULL, "responsibilities" text NOT NULL, "requirements" text NOT NULL, "is_open" boolean NOT NULL, "posted_at" timestamp with time zone NOT NULL);
--
-- Create model JobApplication
--
CREATE TABLE "careers_jobapplication" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "phone" varchar(20) NOT NULL, "resume" varchar(100) NOT NULL, "cover_letter" text NOT NULL, "status" varchar(20) NOT NULL, "created_at" timestamp with time zone NOT NULL, "reviewed_by_id" integer NULL, "opening_id" bigint NOT NULL);
CREATE INDEX "careers_jobopening_slug_d4b8feb4_like" ON "careers_jobopening" ("slug" varchar_pattern_ops);
CREATE INDEX "careers_job_is_open_126931_idx" ON "careers_jobopening" ("is_open");
ALTER TABLE "careers_jobapplication" ADD CONSTRAINT "careers_jobapplication_reviewed_by_id_a90c3ab7_fk_auth_user_id" FOREIGN KEY ("reviewed_by_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "careers_jobapplication" ADD CONSTRAINT "careers_jobapplicati_opening_id_d2be8e03_fk_careers_j" FOREIGN KEY ("opening_id") REFERENCES "careers_jobopening" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "careers_jobapplication_reviewed_by_id_a90c3ab7" ON "careers_jobapplication" ("reviewed_by_id");
CREATE INDEX "careers_jobapplication_opening_id_d2be8e03" ON "careers_jobapplication" ("opening_id");
CREATE INDEX "careers_job_status_3555c2_idx" ON "careers_jobapplication" ("status");
COMMIT;

-- ===== [APP] careers.0002_hr_permissions =====
BEGIN;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
COMMIT;

-- ===== [APP] contact.0001_initial =====
BEGIN;
--
-- Create model Enquiry
--
CREATE TABLE "contact_enquiry" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "phone" varchar(20) NOT NULL, "message" text NOT NULL, "status" varchar(20) NOT NULL, "created_at" timestamp with time zone NOT NULL, "assigned_to_id" integer NULL);
ALTER TABLE "contact_enquiry" ADD CONSTRAINT "contact_enquiry_assigned_to_id_df7d5cfa_fk_auth_user_id" FOREIGN KEY ("assigned_to_id") REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "contact_enquiry_assigned_to_id_df7d5cfa" ON "contact_enquiry" ("assigned_to_id");
CREATE INDEX "contact_enq_status_78e201_idx" ON "contact_enquiry" ("status");
COMMIT;

-- ===== [APP] content.0001_initial =====
BEGIN;
--
-- Create model Award
--
CREATE TABLE "content_award" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "year" integer NOT NULL CHECK ("year" >= 0), "description" text NOT NULL, "image" varchar(100) NULL);
--
-- Create model Download
--
CREATE TABLE "content_download" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "file" varchar(100) NOT NULL, "type" varchar(20) NOT NULL, "created_at" timestamp with time zone NOT NULL);
--
-- Create model FAQ
--
CREATE TABLE "content_faq" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "question" varchar(255) NOT NULL, "answer" text NOT NULL, "category" varchar(20) NOT NULL, "order" integer NOT NULL, "is_active" boolean NOT NULL);
--
-- Create model GalleryItem
--
CREATE TABLE "content_galleryitem" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(180) NOT NULL, "category" varchar(80) NOT NULL, "image" varchar(100) NOT NULL, "order" integer NOT NULL);
--
-- Create model Testimonial
--
CREATE TABLE "content_testimonial" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "author_name" varchar(120) NOT NULL, "designation" varchar(120) NOT NULL, "quote" text NOT NULL, "is_active" boolean NOT NULL, "client_id" bigint NULL);
ALTER TABLE "content_testimonial" ADD CONSTRAINT "content_testimonial_client_id_976cc5d3_fk_core_client_id" FOREIGN KEY ("client_id") REFERENCES "core_client" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "content_testimonial_client_id_976cc5d3" ON "content_testimonial" ("client_id");
COMMIT;

-- ===== [APP] content.0002_alter_testimonial_options =====
BEGIN;
--
-- Change Meta options on testimonial
--
-- (no-op)
COMMIT;

-- ===== [APP] content.0003_alter_download_file =====
BEGIN;
--
-- Alter field file on download
--
-- (no-op)
COMMIT;

-- ===== [FRAMEWORK] contenttypes.0001_initial =====
BEGIN;
--
-- Create model ContentType
--
CREATE TABLE "django_content_type" ("id" integer NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(100) NOT NULL, "app_label" varchar(100) NOT NULL, "model" varchar(100) NOT NULL);
--
-- Alter unique_together for contenttype (1 constraint(s))
--
ALTER TABLE "django_content_type" ADD CONSTRAINT "django_content_type_app_label_model_76bd3d3b_uniq" UNIQUE ("app_label", "model");
COMMIT;

-- ===== [FRAMEWORK] contenttypes.0002_remove_content_type_name =====
BEGIN;
--
-- Change Meta options on contenttype
--
-- (no-op)
--
-- Alter field name on contenttype
--
ALTER TABLE "django_content_type" ALTER COLUMN "name" DROP NOT NULL;
--
-- Raw Python operation
--
-- THIS OPERATION CANNOT BE WRITTEN AS SQL
--
-- Remove field name from contenttype
--
ALTER TABLE "django_content_type" DROP COLUMN "name";
COMMIT;

-- ===== [APP] core.0001_initial =====
BEGIN;
--
-- Create model Industry
--
CREATE TABLE "core_industry" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(120) NOT NULL UNIQUE, "slug" varchar(50) NOT NULL UNIQUE, "icon" varchar(100) NULL);
--
-- Create model Technology
--
CREATE TABLE "core_technology" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(120) NOT NULL UNIQUE, "category" varchar(80) NOT NULL, "icon" varchar(100) NULL);
--
-- Create model Client
--
CREATE TABLE "core_client" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "name" varchar(180) NOT NULL, "slug" varchar(50) NOT NULL UNIQUE, "logo" varchar(100) NULL, "website" varchar(200) NOT NULL, "industry_id" bigint NULL);
CREATE INDEX "core_industry_name_af376edb_like" ON "core_industry" ("name" varchar_pattern_ops);
CREATE INDEX "core_industry_slug_99a95cd7_like" ON "core_industry" ("slug" varchar_pattern_ops);
CREATE INDEX "core_technology_name_adc0a4e9_like" ON "core_technology" ("name" varchar_pattern_ops);
ALTER TABLE "core_client" ADD CONSTRAINT "core_client_industry_id_bf36c8f7_fk_core_industry_id" FOREIGN KEY ("industry_id") REFERENCES "core_industry" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "core_client_slug_40c22521_like" ON "core_client" ("slug" varchar_pattern_ops);
CREATE INDEX "core_client_industry_id_bf36c8f7" ON "core_client" ("industry_id");
COMMIT;

-- ===== [APP] projects.0001_initial =====
BEGIN;
--
-- Create model Project
--
CREATE TABLE "projects_project" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamp with time zone NOT NULL, "updated_at" timestamp with time zone NOT NULL, "title" varchar(200) NOT NULL, "slug" varchar(50) NOT NULL UNIQUE, "status" varchar(20) NOT NULL, "location" varchar(150) NOT NULL, "project_value" varchar(80) NOT NULL, "duration" varchar(60) NOT NULL, "team_size" integer NULL CHECK ("team_size" >= 0), "overview" text NOT NULL, "challenges" text NOT NULL, "solution" text NOT NULL, "thumbnail" varchar(100) NULL, "is_featured" boolean NOT NULL, "order" integer NOT NULL, "client_id" bigint NULL, "industry_id" bigint NOT NULL);
CREATE TABLE "projects_project_technologies" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "project_id" bigint NOT NULL, "technology_id" bigint NOT NULL);
--
-- Create model ProjectDeliverable
--
CREATE TABLE "projects_projectdeliverable" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(180) NOT NULL, "project_id" bigint NOT NULL);
--
-- Create model ProjectGallery
--
CREATE TABLE "projects_projectgallery" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "image" varchar(100) NOT NULL, "caption" varchar(180) NOT NULL, "order" integer NOT NULL, "project_id" bigint NOT NULL);
--
-- Create model ProjectVideo
--
CREATE TABLE "projects_projectvideo" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "video_url" varchar(200) NOT NULL, "title" varchar(150) NOT NULL, "project_id" bigint NOT NULL);
--
-- Create index projects_pr_status_2cea5d_idx on field(s) status, is_featured of model project
--
CREATE INDEX "projects_pr_status_2cea5d_idx" ON "projects_project" ("status", "is_featured");
ALTER TABLE "projects_project" ADD CONSTRAINT "projects_project_client_id_cd971a55_fk_core_client_id" FOREIGN KEY ("client_id") REFERENCES "core_client" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "projects_project" ADD CONSTRAINT "projects_project_industry_id_73ac7df9_fk_core_industry_id" FOREIGN KEY ("industry_id") REFERENCES "core_industry" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "projects_project_slug_2d50067a_like" ON "projects_project" ("slug" varchar_pattern_ops);
CREATE INDEX "projects_project_client_id_cd971a55" ON "projects_project" ("client_id");
CREATE INDEX "projects_project_industry_id_73ac7df9" ON "projects_project" ("industry_id");
ALTER TABLE "projects_project_technologies" ADD CONSTRAINT "projects_project_technol_project_id_technology_id_1c32488b_uniq" UNIQUE ("project_id", "technology_id");
ALTER TABLE "projects_project_technologies" ADD CONSTRAINT "projects_project_tec_project_id_303fe196_fk_projects_" FOREIGN KEY ("project_id") REFERENCES "projects_project" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "projects_project_technologies" ADD CONSTRAINT "projects_project_tec_technology_id_8f5b8cbc_fk_core_tech" FOREIGN KEY ("technology_id") REFERENCES "core_technology" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "projects_project_technologies_project_id_303fe196" ON "projects_project_technologies" ("project_id");
CREATE INDEX "projects_project_technologies_technology_id_8f5b8cbc" ON "projects_project_technologies" ("technology_id");
ALTER TABLE "projects_projectdeliverable" ADD CONSTRAINT "projects_projectdeli_project_id_171b8ea9_fk_projects_" FOREIGN KEY ("project_id") REFERENCES "projects_project" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "projects_projectdeliverable_project_id_171b8ea9" ON "projects_projectdeliverable" ("project_id");
ALTER TABLE "projects_projectgallery" ADD CONSTRAINT "projects_projectgall_project_id_55b3e466_fk_projects_" FOREIGN KEY ("project_id") REFERENCES "projects_project" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "projects_projectgallery_project_id_55b3e466" ON "projects_projectgallery" ("project_id");
ALTER TABLE "projects_projectvideo" ADD CONSTRAINT "projects_projectvide_project_id_22c15e04_fk_projects_" FOREIGN KEY ("project_id") REFERENCES "projects_project" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "projects_projectvideo_project_id_22c15e04" ON "projects_projectvideo" ("project_id");
COMMIT;

-- ===== [APP] projects.0002_beforeaftergallery_projectmilestone =====
BEGIN;
--
-- Create model BeforeAfterGallery
--
CREATE TABLE "projects_beforeaftergallery" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "before_image" varchar(100) NOT NULL, "after_image" varchar(100) NOT NULL, "caption" varchar(180) NOT NULL, "order" integer NOT NULL, "project_id" bigint NOT NULL);
--
-- Create model ProjectMilestone
--
CREATE TABLE "projects_projectmilestone" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "description" text NOT NULL, "date" date NULL, "order" integer NOT NULL, "project_id" bigint NOT NULL);
ALTER TABLE "projects_beforeaftergallery" ADD CONSTRAINT "projects_beforeafter_project_id_95f5e6b4_fk_projects_" FOREIGN KEY ("project_id") REFERENCES "projects_project" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "projects_beforeaftergallery_project_id_95f5e6b4" ON "projects_beforeaftergallery" ("project_id");
ALTER TABLE "projects_projectmilestone" ADD CONSTRAINT "projects_projectmile_project_id_f92bcb15_fk_projects_" FOREIGN KEY ("project_id") REFERENCES "projects_project" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "projects_projectmilestone_project_id_f92bcb15" ON "projects_projectmilestone" ("project_id");
COMMIT;

-- ===== [APP] services.0001_initial =====
BEGIN;
--
-- Create model Service
--
CREATE TABLE "services_service" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "slug" varchar(50) NOT NULL UNIQUE, "short_description" text NOT NULL, "detailed_description" text NOT NULL, "icon" varchar(100) NULL, "is_active" boolean NOT NULL, "order" integer NOT NULL);
CREATE TABLE "services_service_industries" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "service_id" bigint NOT NULL, "industry_id" bigint NOT NULL);
CREATE TABLE "services_service_technologies" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "service_id" bigint NOT NULL, "technology_id" bigint NOT NULL);
--
-- Create model ServiceBenefit
--
CREATE TABLE "services_servicebenefit" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "text" varchar(200) NOT NULL, "service_id" bigint NOT NULL);
--
-- Create model ServiceDeliverable
--
CREATE TABLE "services_servicedeliverable" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(180) NOT NULL, "service_id" bigint NOT NULL);
CREATE INDEX "services_service_slug_a56f96e2_like" ON "services_service" ("slug" varchar_pattern_ops);
ALTER TABLE "services_service_industries" ADD CONSTRAINT "services_service_industr_service_id_industry_id_3d79d2a3_uniq" UNIQUE ("service_id", "industry_id");
ALTER TABLE "services_service_industries" ADD CONSTRAINT "services_service_ind_service_id_b17237d6_fk_services_" FOREIGN KEY ("service_id") REFERENCES "services_service" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "services_service_industries" ADD CONSTRAINT "services_service_ind_industry_id_1fc97cdc_fk_core_indu" FOREIGN KEY ("industry_id") REFERENCES "core_industry" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "services_service_industries_service_id_b17237d6" ON "services_service_industries" ("service_id");
CREATE INDEX "services_service_industries_industry_id_1fc97cdc" ON "services_service_industries" ("industry_id");
ALTER TABLE "services_service_technologies" ADD CONSTRAINT "services_service_technol_service_id_technology_id_f3910194_uniq" UNIQUE ("service_id", "technology_id");
ALTER TABLE "services_service_technologies" ADD CONSTRAINT "services_service_tec_service_id_677bc6ff_fk_services_" FOREIGN KEY ("service_id") REFERENCES "services_service" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "services_service_technologies" ADD CONSTRAINT "services_service_tec_technology_id_fc223d31_fk_core_tech" FOREIGN KEY ("technology_id") REFERENCES "core_technology" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "services_service_technologies_service_id_677bc6ff" ON "services_service_technologies" ("service_id");
CREATE INDEX "services_service_technologies_technology_id_fc223d31" ON "services_service_technologies" ("technology_id");
ALTER TABLE "services_servicebenefit" ADD CONSTRAINT "services_servicebene_service_id_be63e9c8_fk_services_" FOREIGN KEY ("service_id") REFERENCES "services_service" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "services_servicebenefit_service_id_be63e9c8" ON "services_servicebenefit" ("service_id");
ALTER TABLE "services_servicedeliverable" ADD CONSTRAINT "services_servicedeli_service_id_5e53f5e5_fk_services_" FOREIGN KEY ("service_id") REFERENCES "services_service" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "services_servicedeliverable_service_id_5e53f5e5" ON "services_servicedeliverable" ("service_id");
COMMIT;

-- ===== [FRAMEWORK] sessions.0001_initial =====
BEGIN;
--
-- Create model Session
--
CREATE TABLE "django_session" ("session_key" varchar(40) NOT NULL PRIMARY KEY, "session_data" text NOT NULL, "expire_date" timestamp with time zone NOT NULL);
CREATE INDEX "django_session_session_key_c0390e0f_like" ON "django_session" ("session_key" varchar_pattern_ops);
CREATE INDEX "django_session_expire_date_a5c62663" ON "django_session" ("expire_date");
COMMIT;
