# Generated by Django 6.0.6 on 2026-06-30 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_download_file'),
        ('projects', '0002_beforeaftergallery_projectmilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downloads', to='projects.project'),
        ),
    ]
