# Generated by Django 6.0.6 on 2026-06-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_download_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='award',
            options={'ordering': ['-year'], 'verbose_name': 'award', 'verbose_name_plural': 'awards'},
        ),
        migrations.AlterModelOptions(
            name='download',
            options={'ordering': ['-created_at'], 'verbose_name': 'download', 'verbose_name_plural': 'downloads'},
        ),
        migrations.AlterModelOptions(
            name='galleryitem',
            options={'ordering': ['order'], 'verbose_name': 'gallery item', 'verbose_name_plural': 'gallery items'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['-pk'], 'verbose_name': 'testimonial', 'verbose_name_plural': 'testimonials'},
        ),
    ]
